package com.lewandivka.core.registry;

/**
 * One custom sound event. {@code id} is dotted ({@code tram.bell}); the sound files are
 * {@code assets/lewandivka/sounds/<id with dots replaced by '/'>[_n].ogg}, generated by tools/make_sounds.py.
 */
public record SoundSpec(String id, String subtitleUk, String subtitleEn, String category, int variants, boolean stream, float volume) {

    /** Path of the n-th variant without extension ({@code tram/bell_2}). */
    public String file(int n) {
        String base = id.replace('.', '/');
        return variants > 1 ? base + "_" + (n + 1) : base;
    }

    public String subtitleKey() {
        return "subtitles.lewandivka." + id;
    }
}
