"""Ukrainian (canonical) and English texts that are not derived from the Java catalogs: UI, HUD, messages, commands,
config, biomes, credits. Keys used by the game code are checked by tools/validate_resources.py."""

UI = {
    # ---- creative tab, keys
    "itemGroup.lewandivka.main": ("Левандівка", "Lewandivka"),
    "key.categories.lewandivka": ("Левандівка", "Lewandivka"),
    "key.lewandivka.dash": ("Ривок", "Dash"),
    "key.lewandivka.notebook": ("Відкрити блокнот", "Open the notebook"),
    "key.lewandivka.hint": ("Показати підказку", "Show the hint"),
    # ---- dimensions, biomes, titles
    "dimension.lewandivka.district": ("Левандівка", "Lewandivka"),
    "dimension.lewandivka.chromandivka": ("Хромандівка", "Chromandivka"),
    "biome.lewandivka.district": ("Левандівка", "Lewandivka"),
    "biome.lewandivka.chromatic_meadow": ("Кольорова левада", "Chromatic Meadow"),
    "biome.lewandivka.glowshroom_basin": ("Улоговина світлогрибів", "Glowshroom Basin"),
    "biome.lewandivka.orange_riverlands": ("Помаранчеві річки", "Orange Riverlands"),
    "biome.lewandivka.crystal_shelf": ("Кришталева полиця", "Crystal Shelf"),
    "biome.lewandivka.floating_garden": ("Плавучий сад", "Floating Garden"),
    "biome.lewandivka.grey_scar": ("Сірий шрам", "Grey Scar"),
    "biome.lewandivka.dry_lake": ("Сухе озеро", "Dry Lake"),
    "biome.lewandivka.tower": ("Вежа Голови району", "Head of District Tower"),
    "title.lewandivka.district": ("ЛЕВАНДІВКА", "LEWANDIVKA"),
    "title.lewandivka.district.sub": ("Кінцева", "Terminus"),
    "title.lewandivka.chromandivka": ("ХРОМАНДІВКА", "CHROMANDIVKA"),
    "title.lewandivka.chromandivka.sub": ("По той бік району", "The Other Side of the District"),
    # ---- reputation and abilities
    "reputation.lewandivka.stranger": ("Чужий", "Stranger"),
    "reputation.lewandivka.acquaintance": ("Знайомий", "Acquaintance"),
    "reputation.lewandivka.local": ("Свій", "Local"),
    "reputation.lewandivka.district": ("Районний", "District"),
    "ability.lewandivka.dash": ("Ривок", "Dash"),
    "ability.lewandivka.dash.desc": ("Швидкий ривок уперед. Клавіша V.", "A quick burst forward. Key V."),
    "ability.lewandivka.spring_insoles": ("Пружинні устілки", "Spring Insoles"),
    "ability.lewandivka.spring_insoles.desc": ("Високі підскоки на пружинах і м'яке приземлення.", "High bounces on springs and soft landings."),
    "ability.lewandivka.glider": ("Квиток на планер", "Glider Ticket"),
    "ability.lewandivka.glider.desc": ("Стрибок у повітрі розкриває планер на кілька секунд.", "Jump in mid-air to glide for a few seconds."),
    "ability.lewandivka.unlocked": ("Нова здібність: %s", "New ability: %s"),
    "ability.lewandivka.locked": ("Ще не здобуто", "Not unlocked yet"),
    "ability.lewandivka.cooldown": ("Ривок готовий за %s с", "Dash ready in %s s"),
    # ---- notebook screen
    "screen.lewandivka.notebook": ("Районний блокнот", "District Notebook"),
    "screen.lewandivka.notebook.tab.quest": ("Завдання", "Quest"),
    "screen.lewandivka.notebook.tab.history": ("Історія", "History"),
    "screen.lewandivka.notebook.tab.notes": ("Записки", "Notes"),
    "screen.lewandivka.notebook.tab.abilities": ("Здібності", "Abilities"),
    "screen.lewandivka.notebook.active": ("Зараз", "Now"),
    "screen.lewandivka.notebook.hint": ("Підказка", "Hint"),
    "screen.lewandivka.notebook.no_hint": ("Підказки немає. Дивіться навколо.", "No hint. Look around."),
    "screen.lewandivka.notebook.history": ("Вже зроблено", "Done so far"),
    "screen.lewandivka.notebook.no_history": ("Поки нічого.", "Nothing yet."),
    "screen.lewandivka.notebook.notes": ("Знайдені записки", "Notes you found"),
    "screen.lewandivka.notebook.no_notes": ("Ви ще не знайшли жодної записки.", "You have not found any notes yet."),
    "screen.lewandivka.notebook.reputation": ("Репутація: %s", "Reputation: %s"),
    "screen.lewandivka.notebook.tokens": ("Жетони: %s", "Tokens: %s"),
    "screen.lewandivka.notebook.stage": ("Етап: %s", "Stage: %s"),
    "screen.lewandivka.notebook.party": ("Група: %s", "Party: %s"),
    "screen.lewandivka.notebook.page": ("%s / %s", "%s / %s"),
    "screen.lewandivka.notebook.empty": ("Спершу пройдіть пролог.", "Finish the prologue first."),
    "screen.lewandivka.notebook.close": ("Закрити", "Close"),
    "screen.lewandivka.dialogue.continue": ("Далі", "Continue"),
    # ---- HUD
    "hud.lewandivka.chroma": ("ХРОМА", "CHROMA"),
    "hud.lewandivka.chroma.waiting": ("ХРОМА: проковтнули %s з %s", "CHROMA: %s of %s have swallowed it"),
    "hud.lewandivka.chroma.done": ("ХРОМА: усі разом", "CHROMA: all together"),
    "hud.lewandivka.charge": ("Кольоровий заряд: %s с", "Chromatic charge: %s s"),
    "hud.lewandivka.charge.pass": ("Передайте заряд: Q", "Pass the charge: Q"),
    "hud.lewandivka.checkpoint": ("Контрольну точку збережено", "Checkpoint saved"),
    "hud.lewandivka.sync": ("Разом: %s з %s", "Together: %s of %s"),
    "hud.lewandivka.sync.window": ("Вікно: %s с", "Window: %s s"),
    "hud.lewandivka.carrying": ("Посилка повільно бурчить…", "The package is grumbling quietly..."),
    "hud.lewandivka.ticket": ("У вас непробитий квиток! До валідатора!", "Your ticket is unvalidated! Find a validator!"),
    "hud.lewandivka.zone": ("Небезпечна зона: %s", "Dangerous zone: %s"),
    "hud.lewandivka.zone.red": ("червона ✕", "red ✕"),
    "hud.lewandivka.zone.blue": ("синя ◯", "blue ◯"),
    "hud.lewandivka.zone.yellow": ("жовта △", "yellow △"),
    "hud.lewandivka.zone.green": ("зелена ▢", "green ▢"),
    "hud.lewandivka.phase": ("Фаза %s", "Phase %s"),
    "hud.lewandivka.ring": ("Уламки кільця: %s з 4", "Ring fragments: %s of 4"),
    # ---- generic messages
    "message.lewandivka.quest_updated": ("Блокнот оновлено", "The notebook has been updated"),
    "message.lewandivka.quest_started": ("Нове завдання: %s", "New quest: %s"),
    "message.lewandivka.quest_done": ("Завдання виконано: %s", "Quest complete: %s"),
    "message.lewandivka.note_found": ("Записку додано до блокнота", "The note was added to your notebook"),
    "message.lewandivka.note_text": ("«%s»", "\"%s\""),
    "message.lewandivka.stash.empty": ("Тут уже порожньо.", "It is empty here already."),
    "message.lewandivka.stash.found": ("Знайдено: %s", "Found: %s"),
    "message.lewandivka.not_yet": ("Ще не час.", "Not yet."),
    "message.lewandivka.too_far": ("Задалеко.", "Too far away."),
    "message.lewandivka.wrong_stage": ("Це зараз не потрібно.", "That is not needed right now."),
    "message.lewandivka.party_size": ("Група: %s гравц.", "Party size: %s"),
    "message.lewandivka.restored": ("Предмет повернено: %s", "Item restored: %s"),
    "message.lewandivka.restored_checkpoint": ("Предмет чекає на контрольній точці: %s", "The item is waiting at the checkpoint: %s"),
    "message.lewandivka.respawn_checkpoint": ("Ви повернулися до контрольної точки", "You are back at the checkpoint"),
    "message.lewandivka.encounter_reset": ("Зустріч перезапущено", "The encounter was reset"),
    "message.lewandivka.encounter_wipe": ("Усіх переможено. Спробуйте ще раз.", "The whole party fell. Try again."),
    "message.lewandivka.rejoin_delay": ("Повернення до бою за %s с", "Returning to the fight in %s s"),
    # ---- district events
    "message.lewandivka.seeds_taken": ("Гопники взяли сємки і заспокоїлись", "The gopniks took the seeds and calmed down"),
    "message.lewandivka.token_drop": ("Випав жетон району", "A district token dropped"),
    "message.lewandivka.kiosk.need_foundation": ("Кіоск ставлять на розмальований фундамент", "The kiosk goes on the painted foundation"),
    "message.lewandivka.kiosk.placed": ("Кіоск стоїть. Хтось підходить.", "The kiosk stands. Someone approaches."),
    "message.lewandivka.kiosk.unlocked": ("Жетонів вистачає: можна збирати кіоск", "Enough tokens: you can build the kiosk"),
    "message.lewandivka.debtor.clue": ("Знайдено слід Боржника (%s/%s)", "Debtor's trace found (%s/%s)"),
    "message.lewandivka.debtor.caught": ("Боржника наздогнано", "The Debtor is caught"),
    "message.lewandivka.debtor.trips": ("Боржник перечепився", "The Debtor tripped"),
    "message.lewandivka.debtor.need_emeralds": ("Потрібно 3 смарагди", "You need 3 emeralds"),
    "message.lewandivka.debtor.need_tokens": ("Потрібно більше жетонів або репутації", "More tokens or reputation are needed"),
    "message.lewandivka.debtor.need_seeds": ("Потрібно щонайменше 8 сємок", "At least 8 seeds are needed"),
    "message.lewandivka.kettle.fill": ("Чайник набрав води", "The kettle filled with water"),
    "message.lewandivka.kettle.pink": ("Вода на мить стала рожевою", "The water briefly turned pink"),
    "message.lewandivka.garage.power": ("Живлення відновлено: %s з 3", "Power restored: %s of 3"),
    "message.lewandivka.garage.wrong": ("Не те. Автомати скинулися.", "Wrong. The breakers reset."),
    "message.lewandivka.garage.open": ("У стіні між 12 і 14 з'явилися двері", "A door has appeared in the wall between 12 and 14"),
    "message.lewandivka.package.growl": ("Посилка бурчить", "The package growls"),
    "message.lewandivka.package.carry": ("Ви несете посилку. Повільніше.", "You carry the package. Slower."),
    "message.lewandivka.package.placed": ("Посилка лежить. Тихіше.", "The package lies still. Quieter."),
    "message.lewandivka.gate.closed": ("Головні ворота зачинилися", "The main gate has closed"),
    "message.lewandivka.tunnel.open": ("Тунель відчинено ненадовго", "The tunnel is open for a short while"),
    "message.lewandivka.tram.wave": ("Хвиля %s з 3", "Wave %s of 3"),
    "message.lewandivka.tram.shield": ("Щит ватажка спадає: пробийте валідатори (%s/%s)", "The leader's shield weakens: punch the validators (%s/%s)"),
    "message.lewandivka.tram.reward": ("Ви отримали компостер", "You received the composter"),
    "message.lewandivka.chroma.start": ("Хрома: у вас п'ять хвилин. Проковтніть разом.", "Chroma: you have five minutes. Swallow it together."),
    "message.lewandivka.chroma.consumed": ("%s проковтнув(ла) Хрому", "%s swallowed Chroma"),
    "message.lewandivka.chroma.expired": ("Час вийшов. Таблетки лишилися цілі.", "Time ran out. The tablets are untouched."),
    "message.lewandivka.chroma.need_all": ("Ще не всі проковтнули", "Not everyone has swallowed it yet"),
    # ---- Chromandivka events
    "message.lewandivka.pedestal.filled": ("Постамент приймає предмет (%s/%s)", "The pedestal accepts the item (%s/%s)"),
    "message.lewandivka.portal.open": ("Кольоровий портал відчинено", "The Colored Portal is open"),
    "message.lewandivka.battery.taken": ("Ви взяли батарею підйомника (%s/3)", "You took a lift battery (%s/3)"),
    "message.lewandivka.battery.socket": ("Батарею вставлено (%s/3)", "Battery inserted (%s/3)"),
    "message.lewandivka.lift.sync": ("Підйомники: %s з %s", "Lifts: %s of %s"),
    "message.lewandivka.boss.core_open": ("Ядро відкрите! Б'ємо!", "The core is open! Strike!"),
    "message.lewandivka.boss.core_closed": ("Щит повернувся", "The shield is back"),
    "message.lewandivka.boss.defeated": ("Бос переможений", "Boss defeated"),
    "message.lewandivka.boss.enrage": ("Бос розлютився", "The boss is enraged"),
    "message.lewandivka.head.exam": ("Екзамен: усе, чого ви навчилися.", "The exam: everything you have learned."),
    "message.lewandivka.ring.fragment": ("Уламок кільця знайдено", "Ring fragment found"),
    "message.lewandivka.cat.name_hidden": ("???", "???"),
    "message.lewandivka.cat.retreat": ("Кіт відступив до безпечного місця", "The cat retreated to a safe spot"),
    "message.lewandivka.cat.food": ("Кіт підійшов до їжі (%s/%s)", "The cat came to the food (%s/%s)"),
    "message.lewandivka.cat.rug": ("Кіт сів на старий килимок", "The cat sat on the old rug"),
    "message.lewandivka.cat.purr": ("Десь гучніше муркоче…", "The purring is louder somewhere...")  ,
    "message.lewandivka.cat.hidden_route": ("Кіт щось знає про цю стіну", "The cat knows something about this wall"),
    "message.lewandivka.collar.right": ("Коти спокійні: це справжній нашийник", "The cats are calm: this is the real collar"),
    "message.lewandivka.collar.wrong": ("Коти насторожилися: чужий нашийник", "The cats are wary: a strange collar"),
    "message.lewandivka.leash.caught": ("Вас узято на повідець! Знищте якір", "You are leashed! Destroy the anchor"),
    "message.lewandivka.pump.started": ("Насос запущено (%s/3)", "Pump started (%s/3)"),
    "message.lewandivka.pool.filled": ("Басейн наповнюється помаранчевим", "A pool is filling with orange liquid"),
    "message.lewandivka.vortex.zone": ("Зона %s стане небезпечною!", "Zone %s is about to become dangerous!"),
    "message.lewandivka.vortex.drained": ("Зливи закрито. Пані Вирва вразлива!", "Drains finished. Lady Vortex is vulnerable!"),
    "message.lewandivka.drain.core": ("Ядро в зливі (%s/%s)", "Core in the drain (%s/%s)"),
    "message.lewandivka.sky.boarding": ("Небесний трамвай прибув", "The sky tram has arrived"),
    "message.lewandivka.sky.attack": ("Напад на трамвай!", "Attack on the tram!"),
    "message.lewandivka.sky.arrived": ("Трамвайне депо над небом", "Depot Above the Sky"),
    "message.lewandivka.switch.wrong": ("Вагон упирається в тупик і котиться назад", "The car hits a buffer stop and rolls back"),
    "message.lewandivka.switch.ok": ("Колія вільна: вагон доїхав до каси", "The way is clear: the car reached the ticket office"),
    "message.lewandivka.ticket.got": ("Квиток: %s", "Ticket: %s"),
    "message.lewandivka.ticket.validated": ("Квиток дійсний", "The ticket is valid"),
    "message.lewandivka.ticket.invalid": ("Квиток недійсний", "The ticket is invalid"),
    "message.lewandivka.conductor.warning": ("Дзвінок! Трамвай на колії %s", "A bell! A tram on track %s"),
    "message.lewandivka.composter.shield": ("Щит Кондуктора: %s з 3", "Conductor's shield: %s of 3"),
    "message.lewandivka.tower.ticket": ("Ваш номер №%s", "Your number #%s"),
    "message.lewandivka.tower.urgent": ("Терміновий вхід відчинено", "The urgent entrance is open"),
    "message.lewandivka.tower.lever": ("Важіль %s з %s", "Lever %s of %s"),
    "message.lewandivka.tower.paint": ("Фарба змішана", "The paint is mixed"),
    "message.lewandivka.tower.floor": ("Поверх %s", "Floor %s"),
    "message.lewandivka.charge.got": ("У вас кольоровий заряд! %s с", "You have the chromatic charge! %s s"),
    "message.lewandivka.charge.passed": ("Заряд передано: %s", "Charge passed to %s"),
    "message.lewandivka.charge.relay": ("Реле повертає заряд", "The relay returns the charge"),
    "message.lewandivka.charge.overload": ("Заряд перегрівся!", "The charge overheated!"),
    "message.lewandivka.platform.crumbling": ("Платформа втрачає колір", "The platform is losing its colour"),
    "message.lewandivka.final.mono": ("Світ майже втратив колір", "The world has almost lost its colour"),
    "message.lewandivka.epilogue.title": ("Район знову кольоровий", "The District Is Colorful Again"),
    "message.lewandivka.postgame.unlocked": ("Вільна гра відкрита", "Free play unlocked"),
    "message.lewandivka.postgame.cat": ("Кота знайдено: %s (%s з 12)", "Cat found: %s (%s of 12)"),
    "message.lewandivka.postgame.seeds": ("Миска порожня. Хтось ходить уночі.", "The bowl is empty. Someone walks at night."),
    "message.lewandivka.postgame.tram": ("Ви сіли не в той трамвай", "You boarded the wrong tram"),
    "message.lewandivka.postgame.garage0": ("Гараж №0 відчинено", "Garage No. 0 is open"),
    # ---- commands
    "command.lewandivka.status": ("Етап: %s | Крок: %s | Контрольна точка: %s", "Stage: %s | Step: %s | Checkpoint: %s"),
    "command.lewandivka.status.world": ("Боси: %s | Уламки кільця: %s | Портал: %s", "Bosses: %s | Ring fragments: %s | Portal: %s"),
    "command.lewandivka.status.player": ("%s: здібності %s, репутація %s", "%s: abilities %s, reputation %s"),
    "command.lewandivka.checkpoint": ("Контрольну точку збережено", "Checkpoint saved"),
    "command.lewandivka.checkpoint.teleported": ("Телепортовано до контрольної точки", "Teleported to the checkpoint"),
    "command.lewandivka.reset": ("Зустріч «%s» перезапущено", "Encounter \"%s\" was reset"),
    "command.lewandivka.reset.unknown": ("Невідома зустріч: %s", "Unknown encounter: %s"),
    "command.lewandivka.setstage": ("Етап встановлено: %s", "Stage set: %s"),
    "command.lewandivka.setstage.unknown": ("Невідомий етап: %s", "Unknown stage: %s"),
    "command.lewandivka.ability.grant": ("%s отримав здібність %s", "%s was granted %s"),
    "command.lewandivka.ability.revoke": ("%s втратив здібність %s", "%s lost %s"),
    "command.lewandivka.party": ("Розмір групи перевизначено: %s", "Party size overridden: %s"),
    "command.lewandivka.party.cleared": ("Перевизначення розміру групи вимкнено", "Party size override cleared"),
    "command.lewandivka.spawn": ("Створено: %s", "Spawned: %s"),
    "command.lewandivka.teleport": ("Телепортовано: %s", "Teleported: %s"),
    "command.lewandivka.validate": ("Перевірено структур: %s, проблем: %s", "Structures checked: %s, problems: %s"),
    "command.lewandivka.give": ("Видано: %s", "Given: %s"),
    "command.lewandivka.no_permission": ("Недостатньо прав", "Not enough permission"),
    # ---- config
    "config.lewandivka.title": ("Налаштування Левандівки", "Lewandivka Settings"),
    "config.lewandivka.screen_shake": ("Тряска екрана", "Screen shake"),
    "config.lewandivka.flash_reduction": ("Зменшити спалахи", "Reduce flashing"),
    "config.lewandivka.particle_density": ("Щільність частинок", "Particle density"),
    "config.lewandivka.boss_difficulty": ("Складність босів", "Boss difficulty"),
    "config.lewandivka.cinematic_replay": ("Повтор кінематографічних сцен", "Replay cinematics"),
    "config.lewandivka.quest_hints": ("Підказки до завдань", "Quest hints"),
    "config.lewandivka.checkpoint_debug": ("Налагодження контрольних точок", "Checkpoint debug"),
    "config.lewandivka.developer_logs": ("Журнал розробника", "Developer logs"),
    "config.lewandivka.percent": ("%s%%", "%s%%"),
    "config.lewandivka.on": ("Увімкнено", "On"),
    "config.lewandivka.off": ("Вимкнено", "Off"),
    "config.lewandivka.done": ("Готово", "Done"),
    "config.lewandivka.reset": ("Стандартні", "Defaults"),
    # ---- credits
    "credits.lewandivka.title": ("Левандівка: по той бік району", "Lewandivka: The Other Side of the District"),
    "credits.lewandivka.1": ("Район знову кольоровий", "The District Is Colorful Again"),
    "credits.lewandivka.2": ("Ідея, сюжет і дух району — замовник", "Idea, story and the spirit of the district: the client"),
    "credits.lewandivka.3": ("Код, текстури, звуки та світи — створено Claude Code", "Code, textures, sounds and worlds: made by Claude Code"),
    "credits.lewandivka.4": ("Чіназік і Метадонна — за натхненням із референсів замовника", "Chinazik and Metadonna: inspired by the client's references"),
    "credits.lewandivka.5": ("Fabric, Fabric API, GeckoLib — фундамент", "Fabric, Fabric API, GeckoLib: the foundation"),
    "credits.lewandivka.6": ("Sodium, Lithium, FerriteCore, Iris та інші — швидкість і краса", "Sodium, Lithium, FerriteCore, Iris and others: speed and beauty"),
    "credits.lewandivka.7": ("Архітектура району — за мотивами спільноти Planet Minecraft", "District architecture: inspired by the Planet Minecraft community"),
    "credits.lewandivka.8": ("Дякуємо, що пройшли по той бік", "Thank you for crossing to the other side"),
    "credits.lewandivka.9": ("Пан Шлагбаум каже: «Я ж казав.»", "Mr. Shlahbaum says: \"Told you.\""),
}
