package com.lewandivka.world.dimension;

import com.lewandivka.core.world.TerrainColumn;
import com.lewandivka.core.world.WorldPlan;
import com.lewandivka.world.structure.StateResolver;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.registry.DynamicRegistryManager;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.structure.StructureTemplateManager;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.util.math.random.CheckedRandom;
import net.minecraft.util.math.random.ChunkRandom;
import net.minecraft.util.math.random.RandomSeed;
import net.minecraft.world.ChunkRegion;
import net.minecraft.world.HeightLimitView;
import net.minecraft.world.Heightmap;
import net.minecraft.world.SpawnHelper;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.source.BiomeAccess;
import net.minecraft.world.biome.source.BiomeSource;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.gen.GenerationStep;
import net.minecraft.world.gen.StructureAccessor;
import net.minecraft.world.gen.chunk.Blender;
import net.minecraft.world.gen.chunk.ChunkGenerator;
import net.minecraft.world.gen.chunk.VerticalBlockSample;
import net.minecraft.world.gen.chunk.placement.StructurePlacementCalculator;
import net.minecraft.world.gen.noise.NoiseConfig;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;

/**
 * Chunk generator of both Lewandivka dimensions. It does not use noise settings: the terrain, the caves and the quest
 * structures are a pure function of the {@link WorldPlan}, which is what makes the quest structures deterministic. What
 * the biomes of the plan bring (trees, flowers, ores, animals, far-away villages and mineshafts) is generated by the game
 * itself, so the wilderness of the district plays like the ordinary overworld.
 */
public final class PlanChunkGenerator extends ChunkGenerator {

    public static final Codec<PlanChunkGenerator> CODEC = RecordCodecBuilder.create(instance -> instance.group(
            Codec.STRING.fieldOf("plan").forGetter(generator -> generator.planName),
            BiomeSource.CODEC.fieldOf("biome_source").forGetter(generator -> generator.getBiomeSource())
    ).apply(instance, instance.stable(PlanChunkGenerator::new)));

    private final String planName;
    private final WorldPlan plan;

    public PlanChunkGenerator(String planName, BiomeSource biomeSource) {
        super(biomeSource);
        this.planName = planName;
        this.plan = Plans.get(planName);
    }

    public WorldPlan plan() {
        return plan;
    }

    @Override
    protected Codec<? extends ChunkGenerator> getCodec() {
        return CODEC;
    }

    @Override
    public void carve(ChunkRegion chunkRegion, long seed, NoiseConfig noiseConfig, BiomeAccess biomeAccess, StructureAccessor structureAccessor, Chunk chunk, GenerationStep.Carver carverStep) {
    }

    @Override
    public void buildSurface(ChunkRegion region, StructureAccessor structures, NoiseConfig noiseConfig, Chunk chunk) {
    }

    /** The animals of a freshly generated chunk of open country, exactly as the ordinary overworld does it. */
    @Override
    public void populateEntities(ChunkRegion region) {
        ChunkPos chunkPos = region.getCenterPos();
        if (!plan.wilderness(chunkPos.getStartX() + 8, chunkPos.getStartZ() + 8)) {
            return;
        }
        RegistryEntry<Biome> biome = region.getBiome(chunkPos.getStartPos().withY(region.getTopY() - 1));
        ChunkRandom random = new ChunkRandom(new CheckedRandom(RandomSeed.getSeed()));
        random.setPopulationSeed(region.getSeed(), chunkPos.getStartX(), chunkPos.getStartZ());
        SpawnHelper.populateEntities(region, biome, chunkPos, random);
    }

    /**
     * The structures of the ordinary game (villages, mineshafts, ruined portals ...) appear in the wilderness, far enough from
     * the city that none of them can reach its streets: the fixed structures of the quests come from the plan, never from here.
     */
    @Override
    public void setStructureStarts(DynamicRegistryManager registryManager, StructurePlacementCalculator placementCalculator, StructureAccessor structureAccessor,
                                   Chunk chunk, StructureTemplateManager structureTemplateManager) {
        ChunkPos pos = chunk.getPos();
        if (plan.wilderness(pos.getStartX() + 8, pos.getStartZ() + 8) && plan.farFromTheCity(pos.getStartX() + 8, pos.getStartZ() + 8)) {
            super.setStructureStarts(registryManager, placementCalculator, structureAccessor, chunk, structureTemplateManager);
        }
    }

    @Override
    public int getWorldHeight() {
        return plan.height();
    }

    @Override
    public CompletableFuture<Chunk> populateNoise(Executor executor, Blender blender, NoiseConfig noiseConfig, StructureAccessor structureAccessor, Chunk chunk) {
        ChunkPainter.paint(plan, chunk);
        return CompletableFuture.completedFuture(chunk);
    }

    @Override
    public int getSeaLevel() {
        return 62;
    }

    @Override
    public int getMinimumY() {
        return plan.minY();
    }

    @Override
    public int getHeight(int x, int z, Heightmap.Type heightmap, HeightLimitView world, NoiseConfig noiseConfig) {
        TerrainColumn col = new TerrainColumn();
        plan.column(x, z, col);
        int top = Math.max(col.height, col.fluidY);
        boolean solidOnly = heightmap == Heightmap.Type.OCEAN_FLOOR_WG || heightmap == Heightmap.Type.OCEAN_FLOOR;
        return (solidOnly ? col.height : top) + 1;
    }

    @Override
    public VerticalBlockSample getColumnSample(int x, int z, HeightLimitView world, NoiseConfig noiseConfig) {
        TerrainColumn col = new TerrainColumn();
        plan.column(x, z, col);
        int minY = plan.minY();
        BlockState[] states = new BlockState[plan.height()];
        BlockState base = StateResolver.parse(col.base);
        BlockState sub = StateResolver.parse(col.sub);
        BlockState top = StateResolver.parse(col.top);
        BlockState fluid = StateResolver.parse(col.fluid);
        for (int i = 0; i < states.length; i++) {
            int y = minY + i;
            BlockState s;
            if (y > col.height) {
                s = y <= col.fluidY ? fluid : Blocks.AIR.getDefaultState();
            } else if (y == minY) {
                s = Blocks.BEDROCK.getDefaultState();
            } else if (y == col.height) {
                s = top;
            } else if (y >= col.height - col.subDepth) {
                s = sub;
            } else {
                s = base;
            }
            states[i] = s;
        }
        return new VerticalBlockSample(minY, states);
    }

    @Override
    public void getDebugHudText(List<String> text, NoiseConfig noiseConfig, BlockPos pos) {
        text.add("Lewandivka plan: " + planName);
    }
}
