package com.lewandivka.sound;

import com.lewandivka.core.registry.ModSounds;
import com.lewandivka.core.registry.SoundSpec;
import com.lewandivka.util.Ids;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

import java.util.LinkedHashMap;
import java.util.Map;

/** Registers the original sound events of the mod (the audio files are generated by tools/resgen). */
public final class GameSounds {

    private static final Map<String, SoundEvent> EVENTS = new LinkedHashMap<>();

    private GameSounds() {
    }

    public static void register() {
        for (SoundSpec spec : ModSounds.ALL) {
            Identifier id = Ids.of(spec.id());
            EVENTS.put(spec.id(), Registry.register(Registries.SOUND_EVENT, id, SoundEvent.of(id)));
        }
    }

    /** The sound event for a catalog id such as {@code tram.bell}. */
    public static SoundEvent get(String id) {
        SoundEvent e = EVENTS.get(id);
        if (e == null) {
            throw new IllegalArgumentException("unknown sound " + id);
        }
        return e;
    }

    public static boolean has(String id) {
        return EVENTS.containsKey(id);
    }
}
