package com.lewandivka.client.render;

import com.lewandivka.core.registry.EntitySpec;
import net.minecraft.util.Identifier;
import software.bernie.geckolib.core.animatable.GeoAnimatable;
import software.bernie.geckolib.model.GeoModel;

/**
 * The geometry and the animations are shared between entities of the same body plan (humanoid, cat); the texture is
 * the entity's own. All three files are generated by tools/resgen and checked by tools/validate_resources.py.
 */
public final class LewModel<T extends GeoAnimatable> extends GeoModel<T> {

    private final Identifier model;
    private final Identifier texture;
    private final Identifier animation;

    public LewModel(EntitySpec spec) {
        this.model = new Identifier("lewandivka", "geo/entity/" + spec.model + ".geo.json");
        this.texture = new Identifier("lewandivka", "textures/entity/" + spec.texture + ".png");
        this.animation = new Identifier("lewandivka", "animations/entity/" + spec.model + ".animation.json");
    }

    @Override
    public Identifier getModelResource(T animatable) {
        return model;
    }

    @Override
    public Identifier getTextureResource(T animatable) {
        return texture;
    }

    @Override
    public Identifier getAnimationResource(T animatable) {
        return animation;
    }
}
